from __future__ import annotations
import typing
from underautomation.universal_robots.rtde.rtde_output_data_description import RtdeOutputDataDescription
from underautomation.universal_robots.rtde.rtde_output_data import RtdeOutputData
from UnderAutomation.UniversalRobots.Rtde import RtdeOutputsDescription as rtde_outputs_description
from UnderAutomation.UniversalRobots.Rtde import RtdeOutputData as rtde_output_data

class RtdeOutputsDescription:
	def __init__(self, _internal = 0):
		if(_internal == 0):
			self._instance = rtde_outputs_description()
		else:
			self._instance = _internal

	def get(self, data: RtdeOutputData) -> RtdeOutputDataDescription:
		return RtdeOutputDataDescription(self._instance.Get(rtde_output_data(int(data))))

	@property
	def items(self) -> typing.Any:
		return self._instance.Items

	@property
	def timestamp(self) -> RtdeOutputDataDescription:
		'''Time elapsed since the controller was started [s]'''
		return RtdeOutputDataDescription(self._instance.Timestamp)

	@property
	def target_q(self) -> RtdeOutputDataDescription:
		'''Target joint positions'''
		return RtdeOutputDataDescription(self._instance.TargetQ)

	@property
	def target_qd(self) -> RtdeOutputDataDescription:
		'''Target joint velocities'''
		return RtdeOutputDataDescription(self._instance.TargetQd)

	@property
	def target_qdd(self) -> RtdeOutputDataDescription:
		'''Target joint accelerations'''
		return RtdeOutputDataDescription(self._instance.TargetQdd)

	@property
	def target_current(self) -> RtdeOutputDataDescription:
		'''Target joint currents'''
		return RtdeOutputDataDescription(self._instance.TargetCurrent)

	@property
	def target_moment(self) -> RtdeOutputDataDescription:
		'''Target joint moments (torques)'''
		return RtdeOutputDataDescription(self._instance.TargetMoment)

	@property
	def actual_q(self) -> RtdeOutputDataDescription:
		'''Actual joint positions'''
		return RtdeOutputDataDescription(self._instance.ActualQ)

	@property
	def actual_qd(self) -> RtdeOutputDataDescription:
		'''Actual joint velocities'''
		return RtdeOutputDataDescription(self._instance.ActualQd)

	@property
	def actual_current(self) -> RtdeOutputDataDescription:
		'''Actual joint currents'''
		return RtdeOutputDataDescription(self._instance.ActualCurrent)

	@property
	def joint_control_output(self) -> RtdeOutputDataDescription:
		'''Joint control currents'''
		return RtdeOutputDataDescription(self._instance.JointControlOutput)

	@property
	def actual_tcp_pose(self) -> RtdeOutputDataDescription:
		'''Actual Cartesian coordinates of the tool: (x,y,z,rx,ry,rz), where rx, ry and rz is a rotation vector representation of the tool orientation'''
		return RtdeOutputDataDescription(self._instance.ActualTcpPose)

	@property
	def actual_tcp_speed(self) -> RtdeOutputDataDescription:
		'''Actual speed of the tool given in Cartesian coordinates. The speed is given in [m/s] and the rotational part of the TCP speed (rx, ry, rz) is the angular velocity given in [rad/s]'''
		return RtdeOutputDataDescription(self._instance.ActualTcpSpeed)

	@property
	def actual_tcp_force(self) -> RtdeOutputDataDescription:
		'''Generalized forces in the TCP. It compensates the measurement for forces and torques generated by the payload'''
		return RtdeOutputDataDescription(self._instance.ActualTcpForce)

	@property
	def target_tcp_pose(self) -> RtdeOutputDataDescription:
		'''Target Cartesian coordinates of the tool: (x,y,z,rx,ry,rz), where rx, ry and rz is a rotation vector representation of the tool orientation'''
		return RtdeOutputDataDescription(self._instance.TargetTcpPose)

	@property
	def target_tcp_speed(self) -> RtdeOutputDataDescription:
		'''Target speed of the tool given in Cartesian coordinates. The speed is given in [m/s] and the rotational part of the TCP speed (rx, ry, rz) is the angular velocity given in [rad/s]'''
		return RtdeOutputDataDescription(self._instance.TargetTcpSpeed)

	@property
	def actual_digital_input_bits(self) -> RtdeOutputDataDescription:
		'''Current state of the digital inputs. 0-7: Standard, 8-15: Configurable, 16-17: Tool'''
		return RtdeOutputDataDescription(self._instance.ActualDigitalInputBits)

	@property
	def joint_temperatures(self) -> RtdeOutputDataDescription:
		'''Temperature of each joint in degrees Celsius'''
		return RtdeOutputDataDescription(self._instance.JointTemperatures)

	@property
	def actual_execution_time(self) -> RtdeOutputDataDescription:
		'''Controller real-time thread execution time'''
		return RtdeOutputDataDescription(self._instance.ActualExecutionTime)

	@property
	def robot_mode(self) -> RtdeOutputDataDescription:
		'''Robot mode'''
		return RtdeOutputDataDescription(self._instance.RobotMode)

	@property
	def joint_mode(self) -> RtdeOutputDataDescription:
		'''Joint control modes'''
		return RtdeOutputDataDescription(self._instance.JointMode)

	@property
	def safety_mode(self) -> RtdeOutputDataDescription:
		'''Safety mode'''
		return RtdeOutputDataDescription(self._instance.SafetyMode)

	@property
	def safety_status(self) -> RtdeOutputDataDescription:
		'''Safety status'''
		return RtdeOutputDataDescription(self._instance.SafetyStatus)

	@property
	def actual_tool_accelerometer(self) -> RtdeOutputDataDescription:
		'''Tool x, y and z accelerometer values'''
		return RtdeOutputDataDescription(self._instance.ActualToolAccelerometer)

	@property
	def speed_scaling(self) -> RtdeOutputDataDescription:
		'''Speed scaling of the trajectory limiter'''
		return RtdeOutputDataDescription(self._instance.SpeedScaling)

	@property
	def target_speed_fraction(self) -> RtdeOutputDataDescription:
		'''Target speed fraction'''
		return RtdeOutputDataDescription(self._instance.TargetSpeedFraction)

	@property
	def actual_momentum(self) -> RtdeOutputDataDescription:
		'''Norm of Cartesian linear momentum'''
		return RtdeOutputDataDescription(self._instance.ActualMomentum)

	@property
	def actual_main_voltage(self) -> RtdeOutputDataDescription:
		'''Safety Control Board: Main voltage'''
		return RtdeOutputDataDescription(self._instance.ActualMainVoltage)

	@property
	def actual_robot_voltage(self) -> RtdeOutputDataDescription:
		'''Safety Control Board: Robot voltage (48V)'''
		return RtdeOutputDataDescription(self._instance.ActualRobotVoltage)

	@property
	def actual_robot_current(self) -> RtdeOutputDataDescription:
		'''Safety Control Board: Robot current'''
		return RtdeOutputDataDescription(self._instance.ActualRobotCurrent)

	@property
	def actual_joint_voltage(self) -> RtdeOutputDataDescription:
		'''Actual joint voltages'''
		return RtdeOutputDataDescription(self._instance.ActualJointVoltage)

	@property
	def actual_digital_output_bits(self) -> RtdeOutputDataDescription:
		'''Current state of the digital outputs. 0-7: Standard, 8-15: Configurable, 16-17: Tool'''
		return RtdeOutputDataDescription(self._instance.ActualDigitalOutputBits)

	@property
	def runtime_state(self) -> RtdeOutputDataDescription:
		'''Program state'''
		return RtdeOutputDataDescription(self._instance.RuntimeState)

	@property
	def elbow_position(self) -> RtdeOutputDataDescription:
		'''Position of robot elbow in Cartesian Base Coordinates'''
		return RtdeOutputDataDescription(self._instance.ElbowPosition)

	@property
	def elbow_velocity(self) -> RtdeOutputDataDescription:
		'''Velocity of robot elbow in Cartesian Base Coordinates'''
		return RtdeOutputDataDescription(self._instance.ElbowVelocity)

	@property
	def robot_status_bits(self) -> RtdeOutputDataDescription:
		'''Bits 0-3:Is power on | Is program running | Is teach button pressed | Is power button pressed'''
		return RtdeOutputDataDescription(self._instance.RobotStatusBits)

	@property
	def safety_status_bits(self) -> RtdeOutputDataDescription:
		'''Bits 0-10: Is normal mode | Is reduced mode | Is protective stopped | Is recovery mode | Is safeguard stopped | Is system emergency stopped | Is robot emergency stopped | Is emergency stopped | Is violation | Is fault | Is stopped due to safety'''
		return RtdeOutputDataDescription(self._instance.SafetyStatusBits)

	@property
	def analog_io_types(self) -> RtdeOutputDataDescription:
		'''Bits 0-3: analog input 0 | analog input 1 | analog output 0 | analog output 1, {0=current[mA], 1=voltage[V]}'''
		return RtdeOutputDataDescription(self._instance.AnalogIOTypes)

	@property
	def standard_analog_input0(self) -> RtdeOutputDataDescription:
		'''Standard analog input 0 [mA or V]'''
		return RtdeOutputDataDescription(self._instance.StandardAnalogInput0)

	@property
	def standard_analog_input1(self) -> RtdeOutputDataDescription:
		'''Standard analog input 1 [mA or V]'''
		return RtdeOutputDataDescription(self._instance.StandardAnalogInput1)

	@property
	def standard_analog_output0(self) -> RtdeOutputDataDescription:
		'''Standard analog output 0 [mA or V]'''
		return RtdeOutputDataDescription(self._instance.StandardAnalogOutput0)

	@property
	def standard_analog_output1(self) -> RtdeOutputDataDescription:
		'''Standard analog output 1 [mA or V]'''
		return RtdeOutputDataDescription(self._instance.StandardAnalogOutput1)

	@property
	def io_current(self) -> RtdeOutputDataDescription:
		'''I/O current [mA]'''
		return RtdeOutputDataDescription(self._instance.IOCurrent)

	@property
	def euromap67_input_bits(self) -> RtdeOutputDataDescription:
		'''Euromap67 input bits'''
		return RtdeOutputDataDescription(self._instance.Euromap67InputBits)

	@property
	def euromap67_output_bits(self) -> RtdeOutputDataDescription:
		'''Euromap67 output bits'''
		return RtdeOutputDataDescription(self._instance.Euromap67OutputBits)

	@property
	def euromap67_24_v_voltage(self) -> RtdeOutputDataDescription:
		'''Euromap 24V voltage [V]'''
		return RtdeOutputDataDescription(self._instance.Euromap67_24VVoltage)

	@property
	def euromap67_24_v_current(self) -> RtdeOutputDataDescription:
		'''Euromap 24V current [mA]'''
		return RtdeOutputDataDescription(self._instance.Euromap67_24VCurrent)

	@property
	def tool_mode(self) -> RtdeOutputDataDescription:
		'''Tool mode'''
		return RtdeOutputDataDescription(self._instance.ToolMode)

	@property
	def tool_analog_input_types(self) -> RtdeOutputDataDescription:
		'''Output domain {0=current[mA], 1=voltage[V]} Bits 0-1: tool_analog_input_0 | tool_analog_input_1'''
		return RtdeOutputDataDescription(self._instance.ToolAnalogInputTypes)

	@property
	def tool_analog_input0(self) -> RtdeOutputDataDescription:
		'''Tool analog input 0 [mA or V]'''
		return RtdeOutputDataDescription(self._instance.ToolAnalogInput0)

	@property
	def tool_analog_input1(self) -> RtdeOutputDataDescription:
		'''Tool analog input 1 [mA or V]'''
		return RtdeOutputDataDescription(self._instance.ToolAnalogInput1)

	@property
	def tool_output_voltage(self) -> RtdeOutputDataDescription:
		'''Tool output voltage [V]'''
		return RtdeOutputDataDescription(self._instance.ToolOutputVoltage)

	@property
	def tool_output_current(self) -> RtdeOutputDataDescription:
		'''Tool current [mA]'''
		return RtdeOutputDataDescription(self._instance.ToolOutputCurrent)

	@property
	def tool_temperature(self) -> RtdeOutputDataDescription:
		'''Tool temperature in degrees Celsius'''
		return RtdeOutputDataDescription(self._instance.ToolTemperature)

	@property
	def tcp_force_scalar(self) -> RtdeOutputDataDescription:
		'''TCP force scalar [N]'''
		return RtdeOutputDataDescription(self._instance.TcpForceScalar)

	@property
	def output_bit_registers0_to31(self) -> RtdeOutputDataDescription:
		'''General purpose bits'''
		return RtdeOutputDataDescription(self._instance.OutputBitRegisters0To31)

	@property
	def output_bit_registers32_to63(self) -> RtdeOutputDataDescription:
		'''General purpose bits'''
		return RtdeOutputDataDescription(self._instance.OutputBitRegisters32To63)

	@property
	def output_bit_registers(self) -> RtdeOutputDataDescription:
		'''64 general purpose bits. X: [64..127] - The upper range of the boolean output registers can be used by external RTDE clients (i.e URCAPS).'''
		return RtdeOutputDataDescription(self._instance.OutputBitRegisters)

	@property
	def output_int_registers(self) -> RtdeOutputDataDescription:
		'''48 general purpose integer registers. X: [0..23] - The lower range of the integer output registers is reserved for FieldBus/PLC interface usage. X: [24..47] - The upper range of the integer output registers can be used by external RTDE clients (i.e URCAPS).'''
		return RtdeOutputDataDescription(self._instance.OutputIntRegisters)

	@property
	def output_double_registers(self) -> RtdeOutputDataDescription:
		'''48 general purpose double registers. X: [0..23] - The lower range of the double output registers is reserved for FieldBus/PLC interface usage. X: [24..47] - The upper range of the double output registers can be used by external RTDE clients (i.e URCAPS).'''
		return RtdeOutputDataDescription(self._instance.OutputDoubleRegisters)

	@property
	def input_bit_registers0_to31(self) -> RtdeOutputDataDescription:
		'''General purpose bits (input read back). This range of the boolean output registers is reserved for FieldBus/PLC interface usage.'''
		return RtdeOutputDataDescription(self._instance.InputBitRegisters0To31)

	@property
	def input_bit_registers32_to63(self) -> RtdeOutputDataDescription:
		'''General purpose bits (input read back), This range of the boolean output registers is reserved for FieldBus/PLC interface usage.'''
		return RtdeOutputDataDescription(self._instance.InputBitRegisters32To63)

	@property
	def input_bit_registers(self) -> RtdeOutputDataDescription:
		'''64 general purpose bits, X: [64..127] - The upper range of the boolean output registers can be used by external RTDE clients (i.e URCAPS).'''
		return RtdeOutputDataDescription(self._instance.InputBitRegisters)

	@property
	def input_int_registers(self) -> RtdeOutputDataDescription:
		'''48 general purpose integer registers. X: [0..23] - The lower range of the integer input registers is reserved for FieldBus/PLC interface usage. X: [24..47] - The upper range of the integer input registers can be used by external RTDE clients (i.e URCAPS).'''
		return RtdeOutputDataDescription(self._instance.InputIntRegisters)

	@property
	def input_double_registers(self) -> RtdeOutputDataDescription:
		'''48 general purpose double registers. X: [0..23] - The lower range of the double input registers is reserved for FieldBus/PLC interface usage. X: [24..47] - The upper range of the double input registers can be used by external RTDE clients (i.e URCAPS).'''
		return RtdeOutputDataDescription(self._instance.InputDoubleRegisters)

	@property
	def tool_output_mode(self) -> RtdeOutputDataDescription:
		'''The current output mode'''
		return RtdeOutputDataDescription(self._instance.ToolOutputMode)

	@property
	def tool_digital_output0mode(self) -> RtdeOutputDataDescription:
		'''The current mode of digital output 0'''
		return RtdeOutputDataDescription(self._instance.ToolDigitalOutput0mode)

	@property
	def tool_digital_output1_mode(self) -> RtdeOutputDataDescription:
		'''The current mode of digital output 1'''
		return RtdeOutputDataDescription(self._instance.ToolDigitalOutput1Mode)

	@property
	def payload(self) -> RtdeOutputDataDescription:
		'''Payload mass Kg'''
		return RtdeOutputDataDescription(self._instance.Payload)

	@property
	def payload_cog(self) -> RtdeOutputDataDescription:
		'''Payload Center of Gravity (CoGx, CoGy, CoGz) m'''
		return RtdeOutputDataDescription(self._instance.PayloadCOG)

	@property
	def payload_inertia(self) -> RtdeOutputDataDescription:
		'''Payload inertia matrix elements (Ixx,Iyy,Izz,Ixy,Ixz,Iyz] expressed in kg*m^2'''
		return RtdeOutputDataDescription(self._instance.PayloadInertia)

	@property
	def script_control_line(self) -> RtdeOutputDataDescription:
		'''Script line number that is actually in control of the robot given the robot is locked by one of the threads in the script. If no thread is locking the robot this field is set to '0'. Script line number should not be confused with program tree line number displayed on polyscope.'''
		return RtdeOutputDataDescription(self._instance.ScriptControlLine)

	@property
	def ft_raw_wrench(self) -> RtdeOutputDataDescription:
		'''Raw force and torque measurement, not compensated for forces and torques caused by the payload'''
		return RtdeOutputDataDescription(self._instance.FTRawWrench)

	def __str__(self):
		return self._instance.ToString() if self._instance is not None else ""

	def __repr__(self):
		return self.__str__()

	def __eq__(self, other) -> bool:
		if not isinstance(other, RtdeOutputsDescription):
			NotImplemented
		return self._instance.Equals(other._instance)

	def __hash__(self) -> int:
		return self._instance.GetHashCode() if self._instance is not None else 0
