name: CI

on: 
  push:
    tags:
    - 'v*'

jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Build and publish
      run: |
        python -m pip install --upgrade pip
        pip install twine
        pip install --upgrade setuptools
        python setup.py sdist bdist_wheel
        twine upload dist/* -u __token__ -p $PYPI_TOKEN
    - uses: ncipollo/release-action@v1
      with:
        artifacts: ""
        bodyFile: ""
        token: ${{ secrets.GITHUB_TOKEN }}
